// Mocks generated by Mockito 5.4.6 from annotations
// in mafia_game/test/unit/controllers/night_actions_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mafia_game/application/services/audio/audio_controller.dart' as _i3;
import 'package:mafia_game/application/services/theme/theme_controller.dart' as _i14;
import 'package:mafia_game/application/services/network/websocket_controller.dart' as _i6;
import 'package:mafia_game/application/services/game/win_detector.dart' as _i9;
import 'package:mafia_game/domain/models/game/game_phase.dart' as _i5;
import 'package:mafia_game/domain/models/game/game_state.dart' as _i8;
import 'package:mafia_game/domain/models/players/player.dart' as _i11;
import 'package:mafia_game/domain/models/players/player_action.dart' as _i10;
import 'package:mafia_game/domain/models/roles/role.dart' as _i15;
import 'package:mafia_game/domain/models/themes/theme_config.dart' as _i2;
import 'package:mafia_game/infrastructure/services/logging/game_logger.dart' as _i12;
import 'package:mafia_game/infrastructure/services/storage/storage_service.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:web_socket_channel/web_socket_channel.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeThemeConfig_0 extends _i1.SmartFake implements _i2.ThemeConfig {
  _FakeThemeConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AudioController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioController extends _i1.Mock implements _i3.AudioController {
  MockAudioController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> loadTheme(_i2.ThemeConfig? theme) =>
      (super.noSuchMethod(
            Invocation.method(#loadTheme, [theme]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void playBackgroundMusic(_i5.GamePhase? phase) => super.noSuchMethod(
    Invocation.method(#playBackgroundMusic, [phase]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<String?> playEvent(String? eventKey) =>
      (super.noSuchMethod(
            Invocation.method(#playEvent, [eventKey]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> playCompositeEvent(List<String>? eventKeys) =>
      (super.noSuchMethod(
            Invocation.method(#playCompositeEvent, [eventKeys]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> restoreBackground() =>
      (super.noSuchMethod(
            Invocation.method(#restoreBackground, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void stopBackgroundMusic() => super.noSuchMethod(
    Invocation.method(#stopBackgroundMusic, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> stopAll() =>
      (super.noSuchMethod(
            Invocation.method(#stopAll, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [WebSocketController].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketController extends _i1.Mock
    implements _i6.WebSocketController {
  MockWebSocketController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onMessageReceived(void Function(String, Map<String, dynamic>)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onMessageReceived, value),
        returnValueForMissingStub: null,
      );

  @override
  set onConnectionLost(void Function(String)? value) => super.noSuchMethod(
    Invocation.setter(#onConnectionLost, value),
    returnValueForMissingStub: null,
  );

  @override
  void addConnection(String? playerId, _i7.WebSocketChannel? channel) =>
      super.noSuchMethod(
        Invocation.method(#addConnection, [playerId, channel]),
        returnValueForMissingStub: null,
      );

  @override
  void removeConnection(String? playerId) => super.noSuchMethod(
    Invocation.method(#removeConnection, [playerId]),
    returnValueForMissingStub: null,
  );

  @override
  void sendToClient(String? playerId, Map<String, dynamic>? message) =>
      super.noSuchMethod(
        Invocation.method(#sendToClient, [playerId, message]),
        returnValueForMissingStub: null,
      );

  @override
  _i7.WebSocketChannel? getConnection(String? playerId) =>
      (super.noSuchMethod(Invocation.method(#getConnection, [playerId]))
          as _i7.WebSocketChannel?);

  @override
  void broadcast(Map<String, dynamic>? message) => super.noSuchMethod(
    Invocation.method(#broadcast, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void syncClientState(String? playerId, _i8.GameState? state) =>
      super.noSuchMethod(
        Invocation.method(#syncClientState, [playerId, state]),
        returnValueForMissingStub: null,
      );

  @override
  bool validateSession(String? playerId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#validateSession, [playerId, token]),
            returnValue: false,
          )
          as bool);

  @override
  void registerSession(String? playerId, String? token) => super.noSuchMethod(
    Invocation.method(#registerSession, [playerId, token]),
    returnValueForMissingStub: null,
  );

  @override
  void rebindConnection(
    String? oldId,
    String? newId,
    _i7.WebSocketChannel? channel,
  ) => super.noSuchMethod(
    Invocation.method(#rebindConnection, [oldId, newId, channel]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WinDetector].
///
/// See the documentation for Mockito's code generation for more information.
class MockWinDetector extends _i1.Mock implements _i9.WinDetector {
  MockWinDetector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.WinResult? checkWinCondition(List<_i11.Player>? players) =>
      (super.noSuchMethod(Invocation.method(#checkWinCondition, [players]))
          as _i10.WinResult?);
}

/// A class which mocks [GameLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameLogger extends _i1.Mock implements _i12.GameLogger {
  MockGameLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get publicLog =>
      (super.noSuchMethod(
            Invocation.getter(#publicLog),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get detailedLog =>
      (super.noSuchMethod(
            Invocation.getter(#detailedLog),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  void logPublic(String? message) => super.noSuchMethod(
    Invocation.method(#logPublic, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void logDetailed(String? message, {int? level = 800}) => super.noSuchMethod(
    Invocation.method(#logDetailed, [message], {#level: level}),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<String?> exportLog() =>
      (super.noSuchMethod(
            Invocation.method(#exportLog, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i13.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init([String? path]) =>
      (super.noSuchMethod(
            Invocation.method(#init, [path]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveSetting(String? key, dynamic value) =>
      (super.noSuchMethod(
            Invocation.method(#saveSetting, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  dynamic getSetting(String? key) =>
      super.noSuchMethod(Invocation.method(#getSetting, [key]));

  @override
  _i4.Future<void> incrementStat(String? key, [int? amount = 1]) =>
      (super.noSuchMethod(
            Invocation.method(#incrementStat, [key, amount]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  dynamic getStat(String? key, {dynamic defaultValue}) => super.noSuchMethod(
    Invocation.method(#getStat, [key], {#defaultValue: defaultValue}),
  );

  @override
  _i4.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ThemeController].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeController extends _i1.Mock implements _i14.ThemeController {
  MockThemeController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.ThemeMeta> get availableThemes =>
      (super.noSuchMethod(
            Invocation.getter(#availableThemes),
            returnValue: <_i2.ThemeMeta>[],
          )
          as List<_i2.ThemeMeta>);

  @override
  _i4.Future<_i2.ThemeConfig> selectTheme(String? themeId) =>
      (super.noSuchMethod(
            Invocation.method(#selectTheme, [themeId]),
            returnValue: _i4.Future<_i2.ThemeConfig>.value(
              _FakeThemeConfig_0(
                this,
                Invocation.method(#selectTheme, [themeId]),
              ),
            ),
          )
          as _i4.Future<_i2.ThemeConfig>);

  @override
  _i4.Future<void> initializeThemes() =>
      (super.noSuchMethod(
            Invocation.method(#initializeThemes, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  String getRoleDisplayName(_i15.RoleType? role) =>
      (super.noSuchMethod(
            Invocation.method(#getRoleDisplayName, [role]),
            returnValue: _i16.dummyValue<String>(
              this,
              Invocation.method(#getRoleDisplayName, [role]),
            ),
          )
          as String);

  @override
  void setAvailableThemes(List<_i2.ThemeMeta>? themes) => super.noSuchMethod(
    Invocation.method(#setAvailableThemes, [themes]),
    returnValueForMissingStub: null,
  );
}
